/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccessOverlay: typeof import('./components/AccessOverlay.vue')['default']
    Overlay: typeof import('./components/overlay.vue')['default']
    OverlayForm: typeof import('./components/OverlayForm.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResultPage: typeof import('./components/ResultPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./components/SearchResult.vue')['default']
    SearchResults: typeof import('./components/SearchResults.vue')['default']
    Tester: typeof import('./components/Tester.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheMineSelector: typeof import('./components/TheMineSelector.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    TheRegistrationRepresentatives: typeof import('./components/TheRegistrationRepresentatives.vue')['default']
    TheRegistrationVendors: typeof import('./components/TheRegistrationVendors.vue')['default']
    WhiteButton: typeof import('./components/WhiteButton.vue')['default']
  }
}
