/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    RegistrationRepresentatives: typeof import('./components/RegistrationRepresentatives.vue')['default']
    RegistrationVendors: typeof import('./components/RegistrationVendors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tester: typeof import('./components/Tester.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheRegistrationRepresentatives: typeof import('./components/TheRegistrationRepresentatives.vue')['default']
    TheRegistrationVendors: typeof import('./components/TheRegistrationVendors.vue')['default']
  }
}
